language: c

os:
  - linux

dist: bionic

compiler:
  - gcc

branches:
  only:
    - master

# Install dependencies for various OS'
before_install:
  - sudo apt-key update
  - sudo apt-get -y update
  - sudo apt-get -y install build-essential git pkg-config zip unzip software-properties-common python-pip python-dev
  - sudo apt-get -y install libgmp-dev gcc-multilib valgrind openmpi-bin openmpi-doc libopenmpi-dev portmap rpcbind 
  - sudo apt-get -y install libcurl4-openssl-dev bzip2 imagemagick libmagickcore-dev libssl-dev libffi6 libffi-dev llvm 
  - sudo apt-get -y install grpc-cs6200 protobuf-cs6200
  - sudo pip install --upgrade pip
  - sudo pip install --upgrade requests future cryptography pyopenssl ndg-httpsclient pyasn1 nelson
  - sudo apt-get -y -f install gcc gfortran libz-dev m4 bison python python3 make cmake hugo
  - gcc --version && gfortran --version

install:
  ############################################################################
  # Set environment variables
  ############################################################################
  - DEPS_DIR="${HOME}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - export PETSC_DIR=${DEPS_DIR}/petsc
  - export PETSC_ARCH=arch-linux2-c-debug
  - export HDF5_DIR=${PETSC_DIR}/${PETSC_ARCH}/lib
  - export LAGRIT_DIR=${DEPS_DIR}/LaGriT/

  ############################################################################
  # Build PETSc from source
  ############################################################################
  - cd ${DEPS_DIR}
  - git clone https://gitlab.com/petsc/petsc.git petsc && cd petsc
  - git checkout xsdk-0.2.0
  - python2 './configure' '--with-cc=gcc' '--with-cxx=g++' '--with-fc=gfortran' '--download-mpich' '--download-fblaslapack=1' '--download-hdf5=1'
  - make PETSC_DIR=${PETSC_DIR} PETSC_ARCH=${PETSC_ARCH} all
  - cd -

  ############################################################################
  # Get LaGriT
  ############################################################################
  - cd ${DEPS_DIR}
  - git clone https://github.com/lanl/LaGriT.git LaGriT
  - cd -

script:
  - make lglibs
  - make voronoi
  - make docs

deploy:
  provider: pages
  cleanup: true
  local_dir: docs/html
  github_token: $GITHUB_TOKEN
  target_branch: gh-pages
  keep_history: false
  verbose: true
  on:
    branch: master
