baseURL = "/"
publishDir = "html/"
languageCode = "en-us"
title = "VORONOI"
theme = "kube"
relativeURLS=true
description = "VORONOI is a parallel, scalable control volume tessellation generator, built for use in subsurface flow and transport solvers."
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "EES-16 | Los Alamos National Laboratory" # add your company name
  github = "https://www.github.com/lanl/voronoi" # add your github profile name
  twitter = ""
  email = "livingston@lanl.gov"

[[menu.main]]
    name = "About"
    weight = -103
    url = "/docs/about/"
[[menu.main]]
    name = "Documentation"
    weight = -102
    url = "/docs/"
[[menu.main]]
    name = "Publications"
    weight = -101
    url = "/blog/publications/"
[[menu.main]]
    name = "Contact"
    weight = -100
    url = "/blog/contact/"
