# https://raymii.org/s/articles/Github_Actions_cpp_boost_cmake_speedup.html

# This is a basic workflow to help you get started with Actions

name: Build Status 

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # install and cache dependencies
      - name: Install apt-get packages
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc gfortran libz-dev m4 bison python python3 cmake

      - name: Validate tool versions
        run: |
          gcc --version
          gfortran --version
          make --version
          cmake --version

      # Build PETSc
      - name: Build PETSc xsdk-0.2.0
        run: |
          git clone -b release https://gitlab.com/petsc/petsc.git petsc
          cd petsc/ && git checkout xsdk-0.2.0
          python2 './configure' '--with-cc=gcc' '--with-cxx=g++' '--with-fc=gfortran' '--download-mpich' '--download-fblaslapack=1' '--download-hdf5=1'
          

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
